name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.4
      with:
        node-version: 16.x

    - name: install dependencies
      run: yarn

    - name: Run build
      run: yarn build
      env:
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
        APP_KEYS: ${{ secrets.APP_KEYS }}
        API_TOKEN_SALT: ${{ secrets.API_TOKEN_SALT }}
        ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

    - name: Copy project to AGF
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        password: ${{ secrets.SSH_PASS }}
        source: ".,!node_modules"
        target: "~/app/quartz-test-api"

    - name: Run production scripts
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        password: ${{ secrets.SSH_PASS }}
        script: |
          cd ~/app/quartz-test-api
          yarn
          pm2 reload quartz-test-api
