name: Validate PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.4
      with:
        node-version: 12.x

    - name: install dependencies
      run: yarn

    - name: Runnig linter
      run: yarn lint --fix

    - name: Runnig tests
      run: yarn test --bail

    - name: Run build
      run: yarn build
      env:
        REACT_APP_SERVER: ${{ secrets.REACT_APP_SERVER }}
